# Generated by Django 4.2 on 2023-04-14 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_slot_frame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frame',
            name='slots',
        ),
        migrations.AlterField(
            model_name='slot',
            name='slot_name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='SlotValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_name', models.CharField(max_length=200)),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.frame')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.slot')),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.frame')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.slot')),
                ('slot_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.slotvalue')),
            ],
        ),
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.frame')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.slot')),
                ('slot_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.slotvalue')),
            ],
        ),
        migrations.AddField(
            model_name='slot',
            name='frames',
            field=models.ManyToManyField(through='website.Example', to='website.frame'),
        ),
    ]
