# Generated by Django 4.2 on 2023-04-14 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_example_slot_alter_example_slot_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotvalue',
            name='frame',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.frame'),
        ),
        migrations.AlterField(
            model_name='slotvalue',
            name='slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.slot'),
        ),
    ]
