# Generated by Django 4.2 on 2023-04-14 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_slotvalue_frame_alter_slotvalue_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotvalue',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.frame'),
        ),
        migrations.AlterField(
            model_name='slotvalue',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.slot'),
        ),
    ]
