# Generated by Django 4.2 on 2023-04-14 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_slotvalue_frame_alter_slotvalue_slot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dialog',
        ),
    ]
