# Generated by Django 4.2 on 2023-04-14 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_delete_dialog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotvalue',
            name='value_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
