# Generated by Django 4.2 on 2023-04-17 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_slotvalue_value_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='is_matching',
            field=models.BooleanField(default=False),
        ),
    ]
