# Generated by Django 4.2 on 2023-04-17 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_frame_is_matching'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frame',
            name='is_matching',
        ),
    ]
