# Generated by Django 4.2 on 2023-04-20 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_dialog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dialog',
        ),
    ]
